# Default ananicy-cpp configuration bundled with memguard-system-tune
loglevel = info
check_freq = 60
apply_nice = true
apply_sched = true
apply_ionice = true
apply_oom_score_adj = true
apply_latnice = true
cgroup_load = true
type_load = true
rule_load = true
